AWSTemplateFormatVersion: '2010-09-09'
Description: This template creates the infra for the reference solution app.

Parameters:
  pSolutionNaming:
    Type: String
    Description: "Solution naming construct"

  # Use String instead of AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>
  # so we don't need to manage cross account sharing of the AMI id param store
  pLatestAmi:
    Type : String
    Description: AMI ID to for EC2 provisioning

Resources:

  rEC2SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: SSH access
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: 80
        ToPort: 80
        CidrIp: '0.0.0.0/0'

  rWebServer:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !Ref pLatestAmi # Use the latest AMI id
      InstanceType: t2.micro
      SecurityGroups: [!Ref 'rEC2SecurityGroup']
      # UserData sets up a index.php on httpd service to display the ami-id
      UserData: IyEvYmluL2Jhc2gKeXVtIHVwZGF0ZSAteQphbWF6b24tbGludXgtZXh0cmFzIGluc3RhbGwgLXkgbGFtcC1tYXJpYWRiMTAuMi1waHA3LjIgcGhwNy4yCnl1bSBpbnN0YWxsIC15IGh0dHBkIG1hcmlhZGItc2VydmVyCnN5c3RlbWN0bCBzdGFydCBodHRwZApzeXN0ZW1jdGwgZW5hYmxlIGh0dHBkCnVzZXJtb2QgLWEgLUcgYXBhY2hlIGVjMi11c2VyCmNob3duIC1SIGVjMi11c2VyOmFwYWNoZSAvdmFyL3d3dwpjaG1vZCAyNzc1IC92YXIvd3d3CmZpbmQgL3Zhci93d3cgLXR5cGUgZCAtZXhlYyBjaG1vZCAyNzc1IHt9IFw7CmZpbmQgL3Zhci93d3cgLXR5cGUgZiAtZXhlYyBjaG1vZCAwNjY0IHt9IFw7CmV4cG9ydCBJTlNUQU5DRV9BTUlfSUQ9JChjdXJsIGh0dHA6Ly8xNjkuMjU0LjE2OS4yNTQvbGF0ZXN0L21ldGEtZGF0YS9hbWktaWQpCmVjaG8gIjw/cGhwIGVjaG8gIlRoaXMgaW5zdGFuY2UgaXMgY3JlYXRlZCB1c2luZyAkSU5TVEFOQ0VfQU1JX0lEIjsgPz4iID4gL3Zhci93d3cvaHRtbC9pbmRleC5waHA=
      Tags:
        - Key: Name
          Value: !Sub ${pSolutionNaming}-web-instance
